name = "sp-dash-2"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_BASE_URL = "https://dashboard.rareminds.com"

[[services]]
binding = "SSO"
service = "sso-api"
entrypoint = "SsoWorker"

[[queues.producers]]
binding = "MAINTENANCE_EVENTS_QUEUE"
queue = "realtime-events-queue"
